# Generated by Django 5.1.3 on 2024-12-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_alter_song_album_alter_song_genre_alter_song_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='duration',
            field=models.FloatField(default=0.0),
        ),
    ]
