# Generated by Django 5.1.3 on 2024-12-30 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0003_song_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
